name: Sync All LeetCode Submissions

on:
  schedule:
    - cron: "0 0 * * *"   # run daily at midnight UTC
  workflow_dispatch:       # allow manual trigger

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install deps
        run: pip install requests

      - name: Export submissions
        run: python scripts/export_submissions.py
        env:
          LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}
          LEETCODE_CSRF_TOKEN: ${{ secrets.LEETCODE_CSRF_TOKEN }}

      - name: Commit & Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add submissions/
          git commit -m "LeetCode submissions sync on $(date -u)" || echo "No changes"
          git push
